name: Desplegar Angular en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto Angular
        run: npm run build -- --configuration production --base-href /SI2_segundo_parcial_frontend_web/

      - name: Preparar archivos para GitHub Pages
        run: cp ./dist/frontend/browser/index.html ./dist/frontend/browser/404.html

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/frontend/browser
